routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;


Auth::routes();
Route::get('/changeLang/{locale}', 'website\LocalizationController@index');

Route::get('/redirect/{provider}', 'SocialAuthController@redirect');
Route::get('/callback/{provider}', 'SocialAuthController@callback');
Route::get('/logout', 'Auth\LoginController@logout');
Route::get('/about-us', 'website\SettingsController@about_us');
Route::get('/contact-us', 'website\SettingsController@contact');
Route::Post('/contact_us', 'website\SettingsController@contact_us');
Route::get('/terms', 'website\SettingsController@terms');
Route::get('/privacy', 'website\SettingsController@privacy');
Route::get('/adv', 'website\SettingsController@adv');
Route::get('/packages', 'website\SettingsController@packages');

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'website\HomeController@home');
});


Route::group(['prefix' => 'webadmin', 'middleware' => ['webadmin']], function () {
    Route::get('/dashboard', 'admin\DashboardController@index');
    Route::get('/logout', 'Auth\LoginController@logout');
    Route::resource('/users', 'admin\UsersController');
    Route::resource('/admins', 'admin\AdminsController');
    Route::resource('/settings', 'admin\SettingController');
    Route::resource('/categories', 'admin\CategoriesController');
    Route::resource('/subcategories', 'admin\SubCategoriesController');
    Route::resource('/categories-options', 'admin\CategoriesOptionsController');
    Route::resource('/countries', 'admin\CountryController');
    Route::resource('/cities', 'admin\CitiesController');
    Route::resource('/products', 'admin\ProductsController');
    Route::get('/get-product-category-data/{product_id}/{category_id}', 'admin\ProductsController@ProductData');
    Route::resource('/ads', 'admin\AdsController');
    Route::resource('/contacts', 'admin\ContactsController');
    Route::get('/contact/{id}/reply', 'admin\ContactsController@reply');
    Route::post('/contact/{id}/sendreply', 'admin\ContactsController@sendReply');
});
Route::post('/search', 'website\ProductsController@search');
Route::get('/categories/{name}', 'website\ProductsController@getSubCategories');
Route::get('/product/{id}', 'website\ProductsController@getProduct');
Route::get('/products/{cat_id}', 'website\ProductsController@getProducts');
Route::post('/search-filter', 'website\ProductsController@searchFilter');


Route::group(['middleware' => ['auth']], function () {
    Route::get('add-ad', 'website\ProductsController@AddProduct');
    Route::post('/add-ad', 'website\ProductsController@SaveProduct');
    Route::post('/add-ad/image-ajax-upload', 'website\ProductsController@uploadAdImage');
    Route::get('/profile', 'website\UsersController@profile');
    Route::post('/profile', 'website\UsersController@profileUpdate');
    Route::get('/favourites', 'website\UsersController@favourites');
    Route::get('/chats', 'website\UsersController@chats');
    Route::get('/low_price/{product_id}', 'website\ProductsController@lowPrice');
});
Route::get('/information/create/ajax-countries', function () {
    $country_id = $_GET['country_id'];
   $flag =  \App\Models\Country::where('id',$country_id)->select('flag')->first();

    session(['country_id' => $country_id]);
    $flag = $_GET['flag']??$flag->flag;
    session(['flag' => $flag]);
    $cities = \App\Models\City::where('country_id', '=', $country_id)->get();
    return json_encode($cities);

});
Route::get('/information/create/ajax-categories', function () {
    $category_id = $_GET['category_id'];
    $subcategories = \App\Models\Category::where('parent_id', '=', $category_id)->get();
    return json_encode($subcategories);

});
Route::get('/information/create/ajax-types', function () {
    $subcategory_id = $_GET['subcategory_id'];
    $types = \App\Models\Category::where('parent_id', '=', $subcategory_id)->get();
    return json_encode($types);

});
Route::get('/getchat', function () {
    $sender_id = $_GET['sender_id'];
    $receiver_id = $_GET['receiver_id'];
    $messages = \App\Models\Message::where([['sender_id', $sender_id], ['receiver_id', $receiver_id]])
        ->orWhere(function ($query) use ($sender_id, $receiver_id) {
            return $query->where([['sender_id', $receiver_id], ['receiver_id', $sender_id]]);
        })->with('sender')->with('receiver')->get();
    return json_encode($messages);

});
Route::get('/sendmessage', function () {
    $sender_id = $_GET['sender_id'];
    $receiver_id = $_GET['receiver_id'];
    $message = $_GET['message'];
    $msg = \App\Models\Message::create([
        'sender_id' => $sender_id,
        'receiver_id' => $receiver_id,
        'message' => $message,

    ]);
    return json_encode($msg);

});
Route::get('/change-country', function () {
    $country_id = $_GET['country_id'];
    session(['country_id' => $country_id]);

});
Route::get('/change-city', function () {
    $city_id = $_GET['city_id'];
    session(['city_id' => $city_id]);

});

resources/views/admin/admins/add.blade.php
@extends('admin.layouts.app')

@section('title')
   اضافة مدير
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/admins')}}" class="m-menu__link">
            <span class="m-menu__link-text">المدراء</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="" class="m-menu__link">
            <span class="m-menu__link-text">اضافة مدير</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
@endsection

@section('header')



@endsection

@section('content')
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                        اضافة مدير
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        <form class="m-form m-form--fit m-form--label-align-right" action="/webadmin/admins" method="post" enctype="multipart/form-data" >
            <div class="m-portlet__body">
                @csrf
                @include('admin.admins.form')
            </div>
            <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                <div class="m-form__actions m-form__actions--solid">
                    <div class="row">
                        <div class="col-lg-2"></div>
                        <div class="col-lg-6">
                            <button type="submit" class="btn btn-success">اضافة</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')


@endsection

resources/views/admin/admins/edit.blade.php
@extends('admin.layouts.app')

@section('title')
   تعديل مدير
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/admins')}}" class="m-menu__link">
            <span class="m-menu__link-text">المدراء</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="" class="m-menu__link">
            <span class="m-menu__link-text"> تعديل مدير</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
@endsection

@section('header')
@endsection

@section('content')
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                        تعديل مدير
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        {!! Form::model($user,['route' => ['admins.update' , $user->id],'method'=> 'PATCH','class'=>'m-form m-form--fit m-form--label-align-right',"enctype"=>"multipart/form-data"]) !!}
        <div class="m-portlet__body">

            @include('admin.admins.form')
        </div>
        <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
            <div class="m-form__actions m-form__actions--solid">
                <div class="row">
                    <div class="col-lg-2"></div>
                    <div class="col-lg-6">
                        <button type="submit" class="btn btn-success">تعديل</button>
                    </div>
                </div>
            </div>
        </div>
    {!! Form::close() !!}
    <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')
    <script type="text/javascript">

    </script>
@endsection

resources/views/admin/admins/form.blade.php
<div class="form-group m-form__group row">
    <label class="col-lg-1 col-form-label"> الاسم</label>
    <div class="col-lg-5{{ $errors->has('username') ? ' has-danger' : '' }}">
        {!! Form::text('username',old('username'),['class'=>'form-control m-input','autofocus','placeholder'=> 'الاسم' ]) !!}
        @if ($errors->has('username'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('username') }}</strong>
            </span>
        @endif
    </div>
    <label class="col-lg-1 col-form-label">الهاتف</label>
    <div class="col-lg-5{{ $errors->has('phone') ? ' has-danger' : '' }}">
        {!! Form::text('phone',old('phone'),['class'=>'form-control m-input','placeholder'=> 'الهاتف' ]) !!}
        @if ($errors->has('phone'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('phone') }}</strong>
            </span>
        @endif
    </div>




</div>


<div class="form-group m-form__group row">

    <label class="col-lg-1 col-form-label">البريد الالكتروني</label>
    <div class="col-lg-5{{ $errors->has('email') ? ' has-danger' : '' }}">
        {!! Form::text('email',old('email'),['class'=>'form-control m-input','placeholder'=> 'البريد الالكترونى' ]) !!}
        @if ($errors->has('email'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('email') }}</strong>
            </span>
        @endif
    </div>
    <label class="col-lg-1 col-form-label">كلمة المرور </label>
    <div class="col-lg-5{{ $errors->has('password') ? ' has-danger' : '' }}">
        {!! Form::password('password',['class'=>'form-control m-input','placeholder'=> 'كلمة المرور' ]) !!}
        @if ($errors->has('password'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('password') }}</strong>
            </span>
        @endif
    </div>

</div>
<div class="form-group m-form__group row">
    <label class="col-lg-1 col-form-label">الدوله</label>
    <div class="col-lg-5{{ $errors->has('country_id') ? ' has-danger' : '' }}">
        {{--{!! Form::text('phone',old('phone'),['class'=>'form-control m-input','placeholder'=> 'Phone' ]) !!}--}}
        <select name="country_id" id="country_id" class="form-control m-input" >
            <option value="">--اختر الدوله--</option>
            @foreach($countries as $country)
                <option value="{{$country->id}}" {{isset($user) && $user->country_id==$country->id ?'selected':''}}>{{$country->name_ar}}</option>
            @endforeach

        </select>
        @if ($errors->has('country_id'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('country_id') }}</strong>
            </span>
        @endif
    </div>
    <label class="col-lg-1 col-form-label">المدينة</label>
    <div class="col-lg-5{{ $errors->has('city_id') ? ' has-danger' : '' }}">
        <select name="city_id" id="city_id" class="form-control m-input" >
            <option value="">--اختر المدينة --</option>
            @isset($user)
                @foreach($user->country->cities as $city)
                    <option value="{{$city->id}}" {{isset($user) && $user->city_id==$city->id ?'selected':''}}>{{$city->name_ar}}</option>

                @endforeach
            @endisset


        </select>
        @if ($errors->has('city_id'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('city_id') }}</strong>
            </span>
        @endif
    </div>

</div>



<div class="form-group m-form__group row">
    <label class="col-lg-1 col-form-label">الصوره</label>
    <div class="col-lg-11{{ $errors->has('photo') ? ' has-danger' : '' }}">

        <input type="file" name="photo"   class="form-control uploadinput">
        @if ($errors->has('photo'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('photo') }}</strong>
            </span>
        @endif
    </div>

</div>
@if(isset($user) && $user->photo)
    <div class="row">
        
        <div class="col-lg-6 col-md-6 col-sm-6" style="margin-bottom: 10px;">

            <img
                    data-src="holder.js/800x400?auto=yes&amp;bg=777&amp;fg=555&amp;text=First slide"
                    alt="First slide [800x4a00]"
                    src="{{asset($user->photo)}}"
                    style="height: 150px; width: 150px"
                    data-holder-rendered="true">
        </div>

    </div>
@endif

resources/views/admin/admins/index.blade.php
@extends('admin.layouts.app')
@section('title')
    المدراء
@endsection

@section('header')
    {!! Html::style('admin/vendors/custom/datatables/datatables.bundle.rtl.css') !!}
@endsection

@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/admins')}}" class="m-menu__link">
            <span class="m-menu__link-text">المدراء</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>


@endsection

@section('content')
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        المدراء
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <div><a href="{{route('admins.create')}}" style="margin-bottom:20px"
                    class="btn btn_primary btn btn-danger"><i class=" fa fa-edit"></i>اضافة مدير</a></div>
            <br>


            <!--begin: Datatable -->
            <table class="table table-striped- table-bordered table-hover table-checkable search_result"
                   id="m_table_testArea">

                <thead>
                <tr>
                    <th>#</th>
                    <th>الاسم</th>
                    <th>الهاتف</th>
                    <th>البريد الالكترونى</th>
                    <th>الدوله</th>
                    <th>المدينه</th>
                    <th>الادوات</th>
                </tr>
                </thead>
                <tbody>
                @foreach($admins as $index=> $user)
                    <tr>
                        <td>{{++$index}}</td>
                        <td>{{$user->username}} </td>
                        <td>{{$user->phone}} </td>
                        <td>{{$user->email}} </td>
                        <td>{{$user->country->name_ar }} </td>
                        <td>{{$user->city->name_ar }} </td>
                        <td>


                            <a title="عرض" href="/webadmin/admins/{{$user->id}}"><i class="fa fa-eye"></i></a>
                            {{--<a  title="Bank Data" href="/webadmin/user/{{$user->id}}/bank-data" ><i class="fa fa-credit-card"></i></a>--}}
                            <a title="تعديل" href="/webadmin/admins/{{$user->id}}/edit"><i class="fa fa-edit"></i></a>
                            <form class="inline-form-style"
                                  action="/webadmin/admins/{{ $user->id }}"
                                  method="post">
                                <button type="submit" class="trash-btn">
                                    <span class="fa fa-trash"></span>
                                </button>
                                <input type="hidden" name="_method" value="delete"/>
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            </form>

                        </td>
                    </tr>
                @endforeach

                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('footer')
    {{--{!! Html::script('admin/vendors/custom/datatables/datatables.bundle.js') !!}--}}
    {{--{!! Html::script('admin/custom/js/testArea/script.js') !!}--}}

@endsection

resources/views/admin/admins/show.blade.php
@extends('admin.layouts.app')

@section('title')
    تفاصيل المدير
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/admins')}}" class="m-menu__link">
            <span class="m-menu__link-text">المدراء</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="" class="m-menu__link">
            <span class="m-menu__link-text">تفاصيل المدير</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
@endsection

@section('header')
@endsection

@section('content')
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                        تفاصيل المدير
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        {!! Form::model($user,['route' => ['admins.show' , $user->id],'method'=> 'get','class'=>'m-form m-form--fit m-form--label-align-right',"enctype"=>"multipart/form-data"]) !!}
        <div class="m-portlet__body">


            <div class="form-group m-form__group row">
                <label class="col-lg-1 col-form-label">الاسم </label>
                <div class="col-lg-5{{ $errors->has('username') ? ' has-danger' : '' }}">
                    {!! Form::text('username',old('username'),['class'=>'form-control m-input','autofocus','disabled' ]) !!}

                </div>
                <label class="col-lg-1 col-form-label">الهاتف</label>
                <div class="col-lg-5{{ $errors->has('phone') ? ' has-danger' : '' }}">
                    {!! Form::text('phone',old('phone'),['class'=>'form-control m-input','disabled' ]) !!}

                </div>


            </div>


            <div class="form-group m-form__group row">

                <label class="col-lg-2 col-form-label">البريد الالكترونى</label>
                <div class="col-lg-10{{ $errors->has('email') ? ' has-danger' : '' }}">
                    {!! Form::text('email',old('email'),['class'=>'form-control m-input','disabled' ]) !!}

                </div>


            </div>
            <div class="form-group m-form__group row">
                <label class="col-lg-1 col-form-label">الدوله</label>
                <div class="col-lg-5{{ $errors->has('address') ? ' has-danger' : '' }}">
                    <input type="text" class="form-control m-input" value="{{$user->country->name_ar}}" disabled="">

                </div>
                <label class="col-lg-1 col-form-label">المدينه</label>
                <div class="col-lg-5{{ $errors->has('email') ? ' has-danger' : '' }}">
                    <input type="text" class="form-control m-input" value="{{$user->city->name_ar}}" disabled="">
                </div>


            </div>


            @if(isset($user) && $user->photo)
                <div class="row">


                    <div class="col-lg-6 col-md-6 col-sm-6" style="margin-bottom: 10px;">

                        <img
                            data-src="holder.js/800x400?auto=yes&amp;bg=777&amp;fg=555&amp;text=First slide"
                            alt="First slide [800x4a00]"
                            src="{{asset($user->photo)}}"
                            style="height: 150px; width: 150px"
                            data-holder-rendered="true">
                    </div>

                </div>
            @endif



        </div>

    {!! Form::close() !!}
    <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')
    <script type="text/javascript">

    </script>
@endsection