routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;


Auth::routes();
Route::get('/changeLang/{locale}', 'website\LocalizationController@index');

Route::get('/redirect/{provider}', 'SocialAuthController@redirect');
Route::get('/callback/{provider}', 'SocialAuthController@callback');
Route::get('/logout', 'Auth\LoginController@logout');
Route::get('/about-us', 'website\SettingsController@about_us');
Route::get('/contact-us', 'website\SettingsController@contact');
Route::Post('/contact_us', 'website\SettingsController@contact_us');
Route::get('/terms', 'website\SettingsController@terms');
Route::get('/privacy', 'website\SettingsController@privacy');
Route::get('/adv', 'website\SettingsController@adv');
Route::get('/packages', 'website\SettingsController@packages');

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'website\HomeController@home');
});


Route::group(['prefix' => 'webadmin', 'middleware' => ['webadmin']], function () {
    Route::get('/dashboard', 'admin\DashboardController@index');
    Route::get('/logout', 'Auth\LoginController@logout');
    Route::resource('/users', 'admin\UsersController');
    Route::resource('/admins', 'admin\AdminsController');
    Route::resource('/settings', 'admin\SettingController');
    Route::resource('/categories', 'admin\CategoriesController');
    Route::resource('/subcategories', 'admin\SubCategoriesController');
    Route::resource('/categories-options', 'admin\CategoriesOptionsController');
    Route::resource('/countries', 'admin\CountryController');
    Route::resource('/cities', 'admin\CitiesController');
    Route::resource('/products', 'admin\ProductsController');
    Route::get('/get-product-category-data/{product_id}/{category_id}', 'admin\ProductsController@ProductData');
    Route::resource('/ads', 'admin\AdsController');
    Route::resource('/contacts', 'admin\ContactsController');
    Route::get('/contact/{id}/reply', 'admin\ContactsController@reply');
    Route::post('/contact/{id}/sendreply', 'admin\ContactsController@sendReply');
});
Route::post('/search', 'website\ProductsController@search');
Route::get('/categories/{name}', 'website\ProductsController@getSubCategories');
Route::get('/product/{id}', 'website\ProductsController@getProduct');
Route::get('/products/{cat_id}', 'website\ProductsController@getProducts');
Route::post('/search-filter', 'website\ProductsController@searchFilter');


Route::group(['middleware' => ['auth']], function () {
    Route::get('add-ad', 'website\ProductsController@AddProduct');
    Route::post('/add-ad', 'website\ProductsController@SaveProduct');
    Route::post('/add-ad/image-ajax-upload', 'website\ProductsController@uploadAdImage');
    Route::get('/profile', 'website\UsersController@profile');
    Route::post('/profile', 'website\UsersController@profileUpdate');
    Route::get('/favourites', 'website\UsersController@favourites');
    Route::get('/chats', 'website\UsersController@chats');
    Route::get('/low_price/{product_id}', 'website\ProductsController@lowPrice');
});
Route::get('/information/create/ajax-countries', function () {
    $country_id = $_GET['country_id'];
   $flag =  \App\Models\Country::where('id',$country_id)->select('flag')->first();

    session(['country_id' => $country_id]);
    $flag = $_GET['flag']??$flag->flag;
    session(['flag' => $flag]);
    $cities = \App\Models\City::where('country_id', '=', $country_id)->get();
    return json_encode($cities);

});
Route::get('/information/create/ajax-categories', function () {
    $category_id = $_GET['category_id'];
    $subcategories = \App\Models\Category::where('parent_id', '=', $category_id)->get();
    return json_encode($subcategories);

});
Route::get('/information/create/ajax-types', function () {
    $subcategory_id = $_GET['subcategory_id'];
    $types = \App\Models\Category::where('parent_id', '=', $subcategory_id)->get();
    return json_encode($types);

});
Route::get('/getchat', function () {
    $sender_id = $_GET['sender_id'];
    $receiver_id = $_GET['receiver_id'];
    $messages = \App\Models\Message::where([['sender_id', $sender_id], ['receiver_id', $receiver_id]])
        ->orWhere(function ($query) use ($sender_id, $receiver_id) {
            return $query->where([['sender_id', $receiver_id], ['receiver_id', $sender_id]]);
        })->with('sender')->with('receiver')->get();
    return json_encode($messages);

});
Route::get('/sendmessage', function () {
    $sender_id = $_GET['sender_id'];
    $receiver_id = $_GET['receiver_id'];
    $message = $_GET['message'];
    $msg = \App\Models\Message::create([
        'sender_id' => $sender_id,
        'receiver_id' => $receiver_id,
        'message' => $message,

    ]);
    return json_encode($msg);

});
Route::get('/change-country', function () {
    $country_id = $_GET['country_id'];
    session(['country_id' => $country_id]);

});
Route::get('/change-city', function () {
    $city_id = $_GET['city_id'];
    session(['city_id' => $city_id]);

});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = 'categories';
    protected $guarded = [];

    public $timestamps = true;


    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function parent()
    {
        return $this->belongsTo(self::class, 'parent_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function children()
    {
        return $this->hasMany(self::class, 'parent_id', 'id');
    }
}

app/Http/Controllers/admin/CategoriesController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Option;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::where('parent_id', null)->orderBy('created_at', 'ASC')->paginate(10);
        return view('admin.categories.index', compact('categories'));
    }

    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $categories = Category::get();
        $main_categories = Category::where('parent_id', null)->get();
        return view('admin.categories.add', compact('categories', 'main_categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name_ar' => 'required',
            'name_en' => 'required',
            'icon' => 'required',
        ]);

        $category = Category::create($request->except('icon', 'title_ar', 'title_en'));

        if ($request->hasFile('icon')) {
            $request->validate([
                'icon' => 'image|mimes:jpeg,png,jpg,gif,svg'
            ]);

            $imageName = Str::random(10) . '.' . $request->file('icon')->extension();
            $request->file('icon')->move(
                base_path() . '/public/uploads/categories/', $imageName
            );
            $category->icon = '/uploads/categories/' . $imageName;
            $category->save();
        }

        return redirect('/webadmin/categories')->withFlashMessage(json_encode(['success' => true, 'msg' => 'تم اضافة القسم بنجاح']));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        $main_categories = Category::where('parent_id', null)->get();
        $option = Option::where('category_id', $id)->get();
        return view('admin.categories.edit', compact('category', 'main_categories', 'option'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name_ar' => 'required',
            'name_en' => 'required',
        ]);
        $category = Category::find($id);
        $category->update($request->except('icon', 'title_ar', 'title_en', 'option_id'));
        if ($request->hasFile('icon')) {
            $request->validate([
                'icon' => 'image|mimes:jpeg,png,jpg,gif,svg'
            ]);
            $imageName = Str::random(10) . '.' . $request->file('icon')->extension();
            $request->file('icon')->move(
                base_path() . '/public/uploads/categories/', $imageName
            );
            $category->icon = '/uploads/categories/' . $imageName;
            $category->save();
        }

        return redirect('/webadmin/categories')->withFlashMessage(json_encode(['success' => true, 'msg' => 'تم تعديل القسم بنجاح']));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Category::destroy($id);
        return redirect('/webadmin/categories')->withFlashMessage(json_encode(['success' => true, 'msg' => 'تم حذف القسم بنجاح']));
    }
}

resources/views/admin/categories/add.blade.php
@extends('admin.layouts.app')

@section('title')
   اضافة قسم رئيسي رئيسي
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/categories')}}" class="m-menu__link">
            <span class="m-menu__link-text">  الاقسام الرئيسيه</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item" style="background: #e0deff;">
        <a href="" class="m-menu__link">
            <span class="m-menu__link-text">اضافة قسم رئيسي رئيسي</span>
            <i class="m-menu__hor-arrow la la-angle-down"></i>
        </a>
    </li>
@endsection

@section('header')
@endsection

@section('content')

    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                       اضافة قسم رئيسي رئيسي
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        <form class="m-form m-form--fit m-form--label-align-right" action="/webadmin/categories" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}

            <div class="m-portlet__body">
                @include('admin.categories.form')
            </div>
            <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                <div class="m-form__actions m-form__actions--solid">
                    <div class="row">
                        <div class="col-lg-2"></div>
                        <div class="col-lg-6">
                            <button type="submit" class="btn btn-success">اضافة </button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.app')

@section('title')
    تعديل قسم رئيسي
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/categories')}}" class="m-menu__link">
            <span class="m-menu__link-text">الاقسام الرئيسيه </span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item" style="background: #e0deff;">
        <a href="javascript:;" class="m-menu__link">
            <span class="m-menu__link-text">تعديل قسم رئيسي </span>
            <i class="m-menu__hor-arrow la la-angle-down"></i>
        </a>
    </li>
@endsection

@section('header')
@endsection

@section('content')

    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                        تعديل قسم رئيسي
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        {!! Form::model($category,['route' => ['categories.update' , $category->id],'method'=> 'PATCH','class'=>'m-form m-form--fit m-form--label-align-right',"enctype"=>"multipart/form-data"]) !!}
        <div class="m-portlet__body">
            @include('admin.categories.form')
        </div>
        <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
            <div class="m-form__actions m-form__actions--solid">
                <div class="row">
                    <div class="col-lg-2"></div>
                    <div class="col-lg-6">
                        <button type="submit" class="btn btn-success">تعديل</button>
                    </div>
                </div>
            </div>
        </div>
    {!! Form::close() !!}
    <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')
    <script type="text/javascript">

    </script>
@endsection

resources/views/admin/categories/form.blade.php
<div class="form-group m-form__group row">
    <label class="col-lg-2 col-form-label">اسم القسم بالعربية: </label>
    <div class="col-lg-10{{ $errors->has('name_ar') ? ' has-danger' : '' }}">
        {!! Form::text('name_ar',null,['class'=>'form-control m-input','autofocus','placeholder'=>"اسم القسم بالعربية"]) !!}
        @if ($errors->has('name_ar'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('name_ar') }}</strong>
            </span>
        @endif
    </div>
</div>


<div class="form-group m-form__group row">
    <label class="col-lg-2 col-form-label">اسم القسم بالانجليزية: </label>
    <div class="col-lg-10{{ $errors->has('name_en') ? ' has-danger' : '' }}">
        {!! Form::text('name_en',null,['class'=>'form-control m-input','autofocus','placeholder'=>"اسم القسم بالانجليزية"]) !!}
        @if ($errors->has('name_en'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('name_en') }}</strong>
            </span>
        @endif
    </div>
</div>


{{--<div class="form-group m-form__group row">--}}
    {{--<label class="col-lg-2 col-form-label">القسم الرئيسي </label>--}}
    {{--<div class="col-lg-10{{ $errors->has('parent_id') ? ' has-danger' : '' }}">--}}
        {{--<select name="parent_id" id="" class="form-control m-input--solid">--}}
            {{--<option value="">اختر القسم الرئيسي</option>--}}
            {{--@foreach($categories as $main_category)--}}
                {{--<option value="{{$main_category->id}}"--}}
                        {{--@if(isset($category) && $main_category->id == $category->parent_id) selected @endif>{{$main_category->name_ar}}</option>--}}
            {{--@endforeach--}}
        {{--</select>--}}
        {{--<label class="col-lg-10 form-control-label">يمكنك اختار قسم رئيسي في حالة اضافة قسم فرعي </label>--}}
        {{--@if ($errors->has('status'))--}}
            {{--<span class="form-control-feedback" role="alert">--}}
                {{--<strong>{{ $errors->first('status') }}</strong>--}}
            {{--</span>--}}
        {{--@endif--}}
    {{--</div>--}}
{{--</div>--}}




{{--<div class="form-group m-form__group row">--}}
    {{--<label class="col-lg-2 col-form-label">خصائص القسم</label>--}}
    {{--<div class="col-lg-10{{ $errors->has('parent_id') ? ' has-danger' : '' }}">--}}
        {{--<div class="table-responsive">--}}
            {{--<table class="table m-0">--}}
                {{--<thead>--}}
                {{--<tr>--}}
                    {{--<th>#</th>--}}
                    {{--<th>الاسم بالعربيه</th>--}}
                    {{--<th>الاسم بالانجليزيه</th>--}}
                    {{--<th> <a href="javascript:void(0)" onClick="addInput('table_dynamic');" class="btn btn-sm  btn-dark float-left"><span class="fa fa-plus fa-2x"></span></a></th>--}}
                {{--</tr>--}}
                {{--</thead>--}}
                {{--<tbody id="table_dynamic">--}}
                {{--@foreach($option ??[] as $opt)--}}
                {{--<tr>--}}
                    {{--<td><input type="hidden" name="option_id[]" value="{{$opt->id}}">#</td>--}}
                    {{--<td><input name="title_ar[]"  class="form-control" value="{{$opt->name_ar}}" type="text" ></td>--}}
                    {{--<td><input name="title_en[]" class="form-control"  value="{{$opt->name_en}}" type="text" ></td>--}}
                    {{--<td></td>--}}
                {{--</tr>--}}
                {{--@endforeach--}}

                {{--<tr>--}}
                    {{--<td>#</td>--}}
                    {{--<td><input name="title_ar[]"  class="form-control" type="text"></td>--}}
                    {{--<td><input name="title_en[]" class="form-control" type="text"></td>--}}
                    {{--<td></td>--}}
                {{--</tr>--}}
                {{--</tbody>--}}
            {{--</table>--}}
        {{--</div>--}}


    {{--</div>--}}
{{--</div>--}}







<div class="form-group m-form__group row">
    <label class="col-lg-2 col-form-label">الايقونة: </label>
    <div class="col-lg-10{{ $errors->has('icon') ? ' has-danger' : '' }}">

        <input type="file" name="icon" class="form-control uploadinput">
        @if ($errors->has('icon'))
            <span class="form-control-feedback" role="alert">
                <strong>{{ $errors->first('icon') }}</strong>
            </span>
        @endif
    </div>

</div>



@if(isset($category) && $category->icon)
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6" style="margin-bottom: 10px;">
            <img
                data-src="holder.js/800x400?auto=yes&amp;bg=777&amp;fg=555&amp;text=First slide"
                alt="First slide [800x4a00]"
                src="{{$category->icon}}"
                style="height: 150px; width: 150px"
                data-holder-rendered="true">
        </div>
    </div>
@endif

@section('footer')
    <script type="text/javascript">
        let counter = 1;
        let limit = 99;
        function addInput(divName){
            if (counter == limit)  {
                alert("You have reached the limit of adding " + counter + " inputs");
            }
            else {
                let newdiv = document.createElement('tr');
                newdiv.innerHTML = "<td>#</td><td><input name='title_ar[]'  class='form-control' type='text' ></td>" +
                    "<td><input name='title_en[]' class='form-control' type='text' ></td>" +
                    "<td></td>";
                document.getElementById(divName).appendChild(newdiv);
                counter++;
            }
        }

    </script>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.app')
@section('title')
    الاقسام الرئيسيه الرئيسيه
@endsection

@section('header')
    {!! Html::style('admin/vendors/custom/datatables/datatables.bundle.rtl.css') !!}
@endsection

@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item active-top-bar">
        <a href="javascript:;" class="m-menu__link">
            <span class="m-menu__link-text">الاقسام الرئيسيه</span>
            <i class="m-menu__hor-arrow la la-angle-down"></i>
        </a>
    </li>

@endsection

@section('content')
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        الاقسام الرئيسيه
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <div><a href="{{route('categories.create')}}" style="margin-bottom:20px"
                    class="btn btn_primary btn btn-danger"><i class=" fa fa-edit"></i> اضف قسم</a></div>


            <!--begin: Datatable -->
            <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_country">
                <thead>
                <tr>
                    <th>#</th>
                    <th>اسم القسم بالعربية</th>
                    <th>اسم القسم بالانجليزية</th>
                    {{--<th>القسم التابع له</th>--}}
                    <th>الاجراءات</th>
                </tr>
                </thead>
                <tbody>
                @foreach($categories as $index=>$category)
                    <tr>
                        <td>{{$index + $categories->firstItem()}}</td>
                        <td>{{$category->name_ar}}</td>
                        <td>{{$category->name_en}}</td>
{{--                        <td>{{$category->parent ? $category->parent->name_ar : '-----------'}}</td>--}}
                        <td>
                            <a title="تعديل" href="/webadmin/categories/{{$category->id}}/edit"><i
                                    class="fa fa-edit"></i></a>
                            <form class="inline-form-style"
                                  action="/webadmin/categories/{{ $category->id }}"
                                  method="post">
                                <button type="submit" class="trash-btn">
                                    <span class="fa fa-trash"></span>
                                </button>
                                <input type="hidden" name="_method" value="delete"/>
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            {{$categories->links()}}
        </div>
    </div>
@endsection

@section('footer')
    {{--{!! Html::script('admin/vendors/custom/datatables/datatables.bundle.js') !!}--}}
    {{--{!! Html::script('admin/custom/js/countrcountriess!!}--}}
@endsection